### PR TITLE
Merge in latest BoringSSL changes

### PR DESCRIPTION
**Pull request by andrew-kaufman**
### Issues:
Resolves CryptoAlg-577 

### Description of changes: 
This merges in all changes from the tip of the `master` branch of BoringSSL at commit [b67732a163c22da3e056de5cde7b02644ad724db](https://github.com/google/boringssl/commit/b67732a163c22da3e056de5cde7b02644ad724db)

### Call-outs:
The conflicts that needed resolution were in `include/openssl/base.h` and `crypto/trust_token/trust_token_test.cc`.

### Testing:
All unit tests pass.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by torben-hansen** [comment]
> The conflicts that needed resolution were in include/openssl/base.h

What were the conflict(s) in `base.h`?

**Comment by andrew-kaufman** [comment]
We changed two of the macros there in a previous commit to use `AWSLC` instead of `BORINGSSL`.
Also, `OPENSSL_VERSION_NUMBER` and `AWSLC_API_VERSION` values were changed.

**Comment by nebeid** [comment]
Thanks, Andrew, for doing this merge. I reviewed all files with "arm" in their name.
- Are there other particular files you'd like a second look at?
- What were the conflicts in `crypto/trust_token/trust_token_test.cc`?

**Comment by andrew-kaufman** [comment]
> Thanks, Andrew, for doing this merge. I reviewed all files with "arm" in their name.
> 
>     * Are there other particular files you'd like a second look at?
> 
>     * What were the conflicts in `crypto/trust_token/trust_token_test.cc`?

There were changes to two variable names in `trust_token_test.cc`. The first was changing `local_public_metadata` to `parsed_public_metadata` and changing `trusted_token_method` to `method_arg`.

**Comment by bryce-shang** [comment]
> There were changes to two variable names in trust_token_test.cc. The first was changing local_public_metadata to parsed_public_metadata and changing trusted_token_method to method_arg.

The diff looks good.
The conflicts are from my gcc4 fix https://github.com/awslabs/aws-lc/commit/d8c78ceb4ee62510e209ea4d43f1f3319a6c5d3b

**Comment by bryce-shang** [comment]
This merge changes the OpenSSL target from OpenSSL `1.1.0` to `1.1.1`, should new release tag (`1.1.0`) of AWS-LC be created? We may need to check how our branch strategy handles this case.

**Comment by andrew-kaufman** [comment]
The `s2n_integration` target in `aws-lc-ci-linux-x86` will continue to fail because of `OPENSSL_VERSION_NUMBER` being updated to `1.1.1`. A PR has been opened with `s2n` to fix this: https://github.com/awslabs/s2n/pull/2377

**Comment by torben-hansen** [comment]
I'm good with commit `79043e0`.

Please mention it in the description that you needed to add this and why.

**Review by nebeid — APPROVED** [review]

**Review by torben-hansen — APPROVED** [review]

**Pull request merged**
