### PR TITLE
Merge in changes from BoringSSL up to 2021-04-21

### PR DESCRIPTION
**Pull request by andrewhop**
*Description of changes:*
This merges in the complete history up to 2021-04-21 `ab7811ee8751ea699b22095caa70246f641ed3a2`.

Ran the following:
```
git fetch git@github.com:google/boringssl.git ${COMMIT_HASH} 
git merge --strategy recursive --allow-unrelated-histories ${COMMIT_HASH}
git push --set-upstream origin boringmerge
python3 ./util/generate_build_files.py
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by nebeid — DISMISSED** [review]
I followed the review run book, resolving conflicts by inspecting them then copying them over from Andrew's change.

**Comment by bryce-shang** [comment]
What is the plan to `c99` related commits (like [Remove GCC 4.8.99 check.](https://github.com/awslabs/aws-lc/pull/136/commits/49f0329110a1d93a5febc2bceceedc655d995420)) ?

CodeBuild `centos7_gcc4x_x86` and `centos7_gcc4x_x86_64` failed.

> Error log of centos7_gcc4x_x86

```
FAILED: ssl/CMakeFiles/ssl.dir/encrypted_client_hello.cc.o
--
423 | /usr/bin/g++   -DBORINGSSL_DISPATCH_TEST -DBORINGSSL_IMPLEMENTATION -m32 -msse2 -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wvla -ggdb -Wall -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wmissing-declarations -std=c++11 -fno-exceptions -fno-rtti -Wshadow -I../third_party/googletest/include -I../ssl/../include -MMD -MT ssl/CMakeFiles/ssl.dir/encrypted_client_hello.cc.o -MF "ssl/CMakeFiles/ssl.dir/encrypted_client_hello.cc.o.d" -o ssl/CMakeFiles/ssl.dir/encrypted_client_hello.cc.o -c ../ssl/encrypted_client_hello.cc
424 | ../ssl/encrypted_client_hello.cc: In member function 'bool bssl::ECHServerConfig::Init(bssl::Span<const unsigned char>, bssl::Span<const unsigned char>, bool)':
425 | ../ssl/encrypted_client_hello.cc:322:48: error: declaration of 'is_retry_config' shadows a member of 'this' [-Werror=shadow]
426 | bool is_retry_config) {
427 | ^
428 | ../ssl/encrypted_client_hello.cc:322:48: error: declaration of 'private_key' shadows a member of 'this' [-Werror=shadow]
429 | ../ssl/encrypted_client_hello.cc:322:48: error: declaration of 'raw' shadows a member of 'this' [-Werror=shadow]
430 | ../ssl/encrypted_client_hello.cc:348:41: error: declaration of 'public_key' shadows a member of 'this' [-Werror=shadow]
431 | CBS ech_config_contents, public_name, public_key, cipher_suites, extensions;
432 | ^
433 | cc1plus: all warnings being treated as errors


```

**Comment by bryce-shang** [comment]
There is another commit https://github.com/awslabs/aws-lc/pull/136/commits/49f0329110a1d93a5febc2bceceedc655d995420, which `Remove GCC 4.8.99 check`. Need revert?

**Review by bryce-shang — APPROVED** [review]

**Review by bryce-shang — DISMISSED** [review]

**Comment by bryce-shang** [comment]
[AARCH Ubuntu Clang FIPS](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/620771051181/projects/aws-lc-ci-linux-arm/build/aws-lc-ci-linux-arm%3A8cbfd386-c02e-499b-a019-761d160e91f4/?region=us-west-2) stopped because the duration exceeded AWS CodeBuild timeout (2h, set by us).

The dimension has ASAN enabled. ASAN is known to be slow on AARCH. The timeout is because this PR added 1k tests.
```
# PR136
· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·0/0/6993/7000/7942

# main
· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·0/0/6049/6049/6049
```

**Review by bryce-shang — APPROVED** [review]

**Review by nebeid — APPROVED** [review]

**Pull request merged**
